!!python/object:argparse.Namespace
attention_resolutions: 32,16,8
batch_size: 16
channel_mult: ''
class_cond: false
clip_denoised: true
config: ImageNet.yml
diffusion_steps: 1000
dropout: 0.0
image_size: 256
learn_sigma: true
model_path: ''
noise_schedule: linear
num_channels: 256
num_head_channels: 64
num_heads: 4
num_heads_upsample: -1
num_res_blocks: 2
num_samples: 10000
predict_xstart: false
resblock_updown: true
rescale_learned_sigmas: false
rescale_timesteps: false
timestep_respacing: ''
use_checkpoint: false
use_ddim: false
use_fp16: true
use_kl: false
use_new_attention_order: false
use_scale_shift_norm: true
